config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post "/", to: "home#index"

  resources :english_translator, only: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/english_translator_controller.rb
class EnglishTranslatorController <  ActionController::Base

  def new
    english_translator = EnglishTranslator.new
    @result = english_translator.call(params[:word])
    redirect_to controller: :home, action: :index, result: @result
  end

  private

  def english_params
    params.require(:english).permit(:word)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    @result = (params[:result])
	end

  private
  def home_params
    params.require(:home).permit(:result)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    @user = User.find_for_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/english_translator/_translate.html.erb
<br />
<div class= "row">
  <div class="col s8 l6">
    <%= form_for(:word, url: new_english_translator_path, method: :get)  do %>
      <div class = "col s6 l6">
      <%= text_field_tag (:word) %>
      </div>
      <div class = "col s2 l6 valign-wrapper">
      <%= submit_tag 'Translate', class: 'btn valign' %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col s12 l12">
    <p class="blue-text text-darken-3 flow-text">
    <% if !@result.nil? %>
      <% @result.each do |word| %>
        <%= word.upcase%>
      <% end %>
    <% end %>
    <p>
  </div>
</div>

app/views/english_translator/new.html.erb
<%= render 'english_translator/translate' %>

app/views/home/index.html.erb
<%= render 'english_translator/translate' %>

app/views/home/shared/_menu.html.erb
      <nav class="green accent-4 black-text" role="navigation">
        <div class="nav-wrapper container"><%= link_to "English", root_path, id:
                                              "logo-container", class: "brand-logo" %>
          <ul class="right hide-on-med-and-down  blue-grey-text text-darken-4">
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
          </ul>

          <ul id="nav-mobile" class="side-nav green accent-4 blue-grey-text text-darken-4">
              <%= render 'devise/menu/registration_items' %>
              <%= render 'devise/menu/login_items' %>
          </ul>
          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Angielski</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
    <%= render "home/shared/menu" %>
    <div class="container">
      <%= yield %>
       <%= debug(params) if Rails.env.development? %>
    </div>
    </div>
  </body>
</html>